<?php
/**
 * Class file for EbayTradingTypeBotBlockResponseType
 * @date 04/07/2012
 */
/**
 * Class EbayTradingTypeBotBlockResponseType
 * Documentation : Container of token and image URL and Audio URL.
 * @date 04/07/2012
 */
class EbayTradingTypeBotBlockResponseType extends EbayTradingWsdlClass
{
	/**
	 * The BotBlockToken
	 * Meta informations :
	 * 	- minOccurs : 0
	 * 	- documentation : An encrypted token generated by eBay when the botblock mechanism is triggered. This token is mapped to BotBlockUrl and BotBlockAudioUrl.
	 * @var string
	 */
	public $BotBlockToken;
	/**
	 * The BotBlockUrl
	 * Meta informations :
	 * 	- minOccurs : 0
	 * 	- documentation : The URL of the image that your application should display to the user for a botblock challenge.
	 * @var string
	 */
	public $BotBlockUrl;
	/**
	 * The BotBlockAudioUrl
	 * Meta informations :
	 * 	- minOccurs : 0
	 * 	- documentation : The URL of the audio-clip that your application should provide for sight-impaired users. The BotBlockAudioUrl audio-clip corresponds to the BotBlockUrl image.
	 * @var string
	 */
	public $BotBlockAudioUrl;
	/**
	 * The any
	 * @var DOMDocument
	 */
	public $any;
	/**
	 * Constructor
	 * @param string BotBlockToken
	 * @param string BotBlockUrl
	 * @param string BotBlockAudioUrl
	 * @param DOMDocument any
	 * @return EbayTradingTypeBotBlockResponseType
	 */
	public function __construct($_BotBlockToken = null,$_BotBlockUrl = null,$_BotBlockAudioUrl = null,$_any = null)
	{
		parent::__construct(array('BotBlockToken'=>$_BotBlockToken,'BotBlockUrl'=>$_BotBlockUrl,'BotBlockAudioUrl'=>$_BotBlockAudioUrl,'any'=>$_any));
	}
	/**
	 * Set BotBlockToken
	 * @param string BotBlockToken
	 * @return string
	 */
	public function setBotBlockToken($_BotBlockToken)
	{
		return ($this->BotBlockToken = $_BotBlockToken);
	}
	/**
	 * Get BotBlockToken
	 * @return string
	 */
	public function getBotBlockToken()
	{
		return $this->BotBlockToken;
	}
	/**
	 * Set BotBlockUrl
	 * @param string BotBlockUrl
	 * @return string
	 */
	public function setBotBlockUrl($_BotBlockUrl)
	{
		return ($this->BotBlockUrl = $_BotBlockUrl);
	}
	/**
	 * Get BotBlockUrl
	 * @return string
	 */
	public function getBotBlockUrl()
	{
		return $this->BotBlockUrl;
	}
	/**
	 * Set BotBlockAudioUrl
	 * @param string BotBlockAudioUrl
	 * @return string
	 */
	public function setBotBlockAudioUrl($_BotBlockAudioUrl)
	{
		return ($this->BotBlockAudioUrl = $_BotBlockAudioUrl);
	}
	/**
	 * Get BotBlockAudioUrl
	 * @return string
	 */
	public function getBotBlockAudioUrl()
	{
		return $this->BotBlockAudioUrl;
	}
	/**
	 * Set any
	 * @param DOMDocument any
	 * @return DOMDocument
	 */
	public function setAny($_any)
	{
		return ($this->any = $_any);
	}
	/**
	 * Get any
	 * @return DOMDocument
	 */
	public function getAny()
	{
		if(!($this->any instanceof DOMDocument))
		{
			$dom = new DOMDocument('1.0','UTF-8');
			$dom->formatOutput = true;
			$dom->loadXML($this->any);
			$this->setAny($dom);
		}
		return $this->any;
	}
	/**
	 * Method returning the class name
	 * @return string __CLASS__
	 */
	public function __toString()
	{
		return __CLASS__;
	}
}
?>